### ISSUE TITLE
in order try it needs fpga toolkit , but where to buy?

### ISSUE THREAD

**Issue by Sandy4321** [ucb-bar/fpga-zynq#28]
in order try it for machine learning it needs fpga toolkit , but where to buy?

**Comment by davidbiancolin** [comment]
The boards supported (immediately) by this repo, in order of ascending cost, are:
http://store.digilentinc.com/zybo-zynq-7000-arm-fpga-soc-trainer-board/
http://store.digilentinc.com/zedboard-zynq-7000-arm-fpga-soc-development-board/
https://www.xilinx.com/products/boards-and-kits/ek-z7-zc706-g.html

You may pick your poison.
