### ISSUE TITLE
How to put files into riscv-linux?

### ISSUE THREAD

**Issue by chencunyen** [ucb-bar/fpga-zynq#46]
Hi,

I follow the step 3.8 [https://github.com/ucb-bar/fpga-zynq#38--booting-up-and-interacting-with-the-risc-v-rocket-core](url) to boot riscv-linux on zedboard, after that, it booted successfully. The question is, I don't know how to put files into riscv-linux through mount or ethernet, do I need to rebuild the busybox to enable network interface?  If not, are there any easy ways to put files on riscv-linux?

Thanks for your help!

**Comment by davidbiancolin** [comment]
If you want to add files to the core you'll need to need to add them to an initramfs.

**Comment by muhammadali201** [comment]
@davidbiancolin  How can you add files to initramfs?
