### ISSUE TITLE
How to add my programs into uarmdisk.image.gz

### ISSUE THREAD

**Issue by Pengnian** [ucb-bar/fpga-zynq#49]
Hi all,

I have implemented loading rocket to my zedboard , want add my compiled programs into RAM linux (ur amdisk.image.gz) to running,just like hello(./fesvr-zynq pk hello).But I don't know what to do, plaese help me.Thanks~

**Comment by davidbiancolin** [comment]
If you want to add programs that you can run on top of PK, you just need to include the compiled programs in the ARM's ramdisk. 

see Appendix B, and  make ```ramdisk_open``` and ```make ramdisk_close```.  Navigate into the home directory within the ramdisk and you should find the default bbl, pk, and hello we provide.

**Comment by Pengnian** [comment]
@David Biancolin  Thanks very much! 😁

**Comment by Pengnian** [comment]
@davidbiancolin hello, you can tell me the details about  how to use command "make ramdisk_open "  " make ramdisk_close", I just entering the directory of "uramdisk.image.gz",then  used commands. If you can tell me the details of operation,I will appreciate you very much.

**Comment by ben-k** [comment]
You need to run these commands from the directory corresponding to your FPGA.  For example, from the root of the repo:

```
cd zedboard
make ramdisk-open
```

Note that the command uses a dash, not an underscore (this is correct in the README but not in the above comment).  Otherwise, just follow the instructions in the README.

**Comment by davidbiancolin** [comment]
Oh dear. Thanks ben.

**Comment by Pengnian** [comment]
@davidbiancolin @ben-k  oh,thanks two guys

I'm a beginner,your guides important for me,thanks for you patience !

**Comment by davidbiancolin** [comment]
I'm closing this; reopen if you need a bit more help.

**Comment by ninode** [comment]
Hi @Pengnian, did you manage to add programs and run them with the command ? 
Have you tired to run any programs for GPIO ? 
Thanks
