### ISSUE TITLE
Hello World not working after bitfile regeneration

### ISSUE THREAD

**Issue by crolfes** [ucb-bar/fpga-zynq#5]
Hi,

the prebuild images for the zedboard run fine.
```
root@zynq:~# ./fesvr-zynq pk hello
hello!
```

But when I create my own bitfile with Vivado (2014 or 2015, doesn’t matter) the Hello World test progam
produces no output any more. Seems like it stucks.
I execute the commands like in your tutorial "2) Pushing Your Rocket Modifications to the FPGA”

Then I replace the file boot.bin on the SD card. But I cannot communicate with the RISCV any more.

**Comment by sbeamer** [comment]
This seems to be the same issue as #4, so I'm going to close this one and work on that one.
