### ISSUE TITLE
Error " ../pk/elf.c:46: assertion failed: !(eh.e_flags) & EF_RISCV_RVC " . 

### ISSUE THREAD

**Issue by Pengnian** [ucb-bar/fpga-zynq#51]
I installed riscv-tools on my ubuntu system. Then I wrote a simple hello world program in C. I cross compiled it using "riscv64-unknown-elf-gcc -O2 -o hello1 hello.c". Then I dumped the executable file on petalinux on zedboard, connected to my PC via UART. Here is the problem. While running this "hello" file, I get this error " ../pk/elf.c:46: assertion failed: !(eh.e_flags) & EF_RISCV_RVC " .

**Comment by davidbiancolin** [comment]
Smells like you're using an incompatible version of the toolchain. Make sure you build the toolchain from the version of riscv-tools that is included in the rocket-chip pointer of this repository. Specifically, [this one](https://github.com/riscv/riscv-tools/tree/6136df9cba56afe12c2fa321ef497090917c15aa).
