### ISSUE TITLE
Make rocket error

### ISSUE THREAD

**Issue by kllbrd** [ucb-bar/fpga-zynq#53]
[root@localhost zedboard]# make rocket
bash /usr/local/fpga-zynq/common/generate-pkg-mk.sh testchipip > /usr/local/fpga-zynq/common/Makefrag.pkgs
cd /usr/local/rocket-chip && java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /usr/local/rocket-chip/sbt-launch.jar pack
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Loading project definition from /usr/local/rocket-chip/project
Using addons: 
[info] Set current project to rocketchip (in build file:/usr/local/rocket-chip/)
[info] Compiling 1 Scala source to /usr/local/rocket-chip/chisel3/target/scala-2.11/classes...
[info] Packaging /usr/local/rocket-chip/chisel3/target/scala-2.11/chisel3_2.11-3.1-SNAPSHOT.jar ...
[info] Done packaging.
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Creating a distributable package in target/pack
[info] Copying libraries to target/pack/lib
[info] project jars:
[info] target/scala-2.11/rocketchip_2.11-1.2.jar
[info] chisel3/target/scala-2.11/chisel3_2.11-3.1-SNAPSHOT.jar
[info] chisel3/coreMacros/target/scala-2.11/coremacros_2.11-3.1-SNAPSHOT.jar
[info] chisel3/chiselFrontend/target/scala-2.11/chiselfrontend_2.11-3.1-SNAPSHOT.jar
[info] hardfloat/target/scala-2.11/hardfloat_2.11-1.2.jar
[info] project dependencies:
[info] org.scala-lang:scala-reflect:2.11.7
[info] com.github.scopt:scopt_2.11:3.4.0
[info] org.scala-lang:scala-library:2.11.7
[info] unmanaged dependencies:
[info] /usr/local/rocket-chip/lib/firrtl.jar
[info] /usr/local/rocket-chip/lib/firrtl.jar
[info] /usr/local/rocket-chip/lib/firrtl.jar
[info] /usr/local/rocket-chip/lib/firrtl.jar
[info] explicit dependencies:
[info] Create a bin folder: target/pack/bin
[info] Generating launch scripts
[info] main class for generator: unittest.Generator
[info] Generating target/pack/bin/generator
[info] Generating target/pack/bin/generator.bat
[info] main class for driver: chisel3.Driver
[info] Generating target/pack/bin/driver
[info] Generating target/pack/bin/driver.bat
[info] main class for fma-test: hardfloat.FMATest
[info] Generating target/pack/bin/fma-test
[info] Generating target/pack/bin/fma-test.bat
[info] packed resource directories = /usr/local/rocket-chip/src/pack
[info] Generating target/pack/Makefile
[info] Generating target/pack/VERSION
[info] done.
[success] Total time: 6 s, completed Jul 7, 2017 7:45:55 PM
mkdir -p /usr/local/fpga-zynq/common/lib
cp /usr/local/rocket-chip/target/pack/lib/* /usr/local/fpga-zynq/common/lib
touch /usr/local/fpga-zynq/common/lib/rocketchip.stamp
rm -f /usr/local/fpga-zynq/common/../testchipip/lib
ln -s /usr/local/fpga-zynq/common/lib /usr/local/fpga-zynq/common/../testchipip/lib
cd /usr/local/fpga-zynq/common/../testchipip && java -Xmx2G -Xss8M -XX:MaxPermSize=256M -jar /usr/local/rocket-chip/sbt-launch.jar package
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
[info] Set current project to testchipip (in build file:/usr/local/fpga-zynq/testchipip/)
[info] Updating {file:/usr/local/fpga-zynq/testchipip/}testchipip...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Packaging /usr/local/fpga-zynq/testchipip/target/scala-2.10/testchipip_2.10-0.1-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 1 s, completed Jul 7, 2017 7:45:59 PM
cp /usr/local/fpga-zynq/common/../testchipip/target/scala-2.11/*.jar /usr/local/fpga-zynq/common/lib
cp: cannot stat '/usr/local/fpga-zynq/common/../testchipip/target/scala-2.11/*.jar': No such file or directory
/usr/local/fpga-zynq/common/Makefrag.pkgs:2: recipe for target '/usr/local/fpga-zynq/common/lib/testchipip.stamp' failed
make: *** [/usr/local/fpga-zynq/common/lib/testchipip.stamp] Error 1

That happens because in this: /fpga-zynq/testchipip/target there is this: scala-2.10 and not 2.11.
I changed it from common/Makefrag.pkgs to 2.10, the error gone but I got a bunch of other errors situated in:
1.   /usr/local/fpga-zynq/common/src/main/scala/Configs.scala
2.   /usr/local/fpga-zynq/common/src/main/scala/SerialDriver.scala
3.   /usr/local/fpga-zynq/common/src/main/scala/Top.scala
4.   /usr/local/fpga-zynq/common/src/main/scala/TestHarness.scala
(sum of 72 errors)
Taking this: 
[error] Total time: 5 s, completed Jul 7, 2017 7:19:11 PM
../common/Makefrag:85: recipe for target '/usr/local/fpga-zynq/common/build/Top.ZynqConfig.fir' failed
make: *** [/usr/local/fpga-zynq/common/build/Top.ZynqConfig.fir] Error 1

What I'm doing wrong?
Any kind of help would be appreciated.
Thanks!

**Comment by kllbrd** [comment]
solved

**Comment by ninode** [comment]
Hi @kllbrd, How did you solve it ? Did you initialize testchipip ?
Also, did make bitstream work ?

**Comment by kllbrd** [comment]
Hello @ninode,
Initially I tried to give the path of my rocket-chip directory in fpga-zynq/common/Makefrag. 
Then I decide to have my fpga-zynq directory fully updated so I initialized both rocket-chip dir and testchipip.
So, yes, in essence that was the solution to this problem.
All the tools now are working properly, I have my zedboard running on rocket.
Greetings.
