### ISSUE TITLE
Changing RAMDisk

### ISSUE THREAD

**Issue by ninode** [ucb-bar/fpga-zynq#54]
Hello, 

Linux is running out of a RAMdisk and uramdisk.image.gz holds Linux for the ARM cores.  

What could be changed by running make ramdisk-open ?

Thank you

**Comment by ben-k** [comment]
You can change any of the Linux system files that are used in the OS of the ARM core.  For example, a common setting that you might want to change is the default IP address of the system (in `/etc/network/interfaces`).

**Comment by davidbiancolin** [comment]
It's probably easiest if you use a larger SD card/use a larger partition. But yes, you could technically prune down the linux ramdisk; i'd advise against that.
