### ISSUE TITLE
Frequency of vivado project

### ISSUE THREAD

**Issue by ViccoYang** [ucb-bar/fpga-zynq#57]
I follow the README and generate a default rocket-chip vivado project(zedboard) , but the frequency is only 25MHz. Would you please give me some advice to improve the frequency?

**Comment by ben-k** [comment]
It looks like the synthesis constraints can be edited in [this file](zedboard/src/constrs/base.xdc).

However, I doubt you'll be able to push the frequency of Rocket Chip much above 25MHz.  The codebase was optimized for ASIC designs, not FPGAs, and the FPGA tools struggle with register retiming that is expected for the pipelined FPU (see #30).
