### ISSUE TITLE
Instructions not working on Zedboard

### ISSUE THREAD

**Issue by kllbrd** [ucb-bar/fpga-zynq#59]
I followed all the steps, with the Zed booting properly when I login and run
`./fesvr-zynq pk hello`
or
`./fesvr-zynq bbl`
the system stucks without the possibility to interrupt with Ctrl+C.

My SD's directory environment:
SD/
-bbl
-BOOT.bin
-uImage
-devicetree.dtb
-uramdisk.image.gz

Any kind of help would be appreciated.
Thanks.

**Comment by davidbiancolin** [comment]
Are you using the provided images, including the BBL and PK provided there?

**Comment by kllbrd** [comment]
No that wasn't a problem. This is solved... 
Thanks anyway!

**Comment by clx7913** [comment]
@kllbrd Could you tell me how do you make it work?
I have the same problem.My board is also Zedboard and "./fesvr-zynq pk hello"  also doesn't work.
