### ISSUE TITLE
make arm-linux error

### ISSUE THREAD

**Issue by clx7913** [ucb-bar/fpga-zynq#74]
Following the README.md,I encountered some errors when I input "make arm-linux".A part of the log is below:

cd /home/chang/fpga-zynq/common/linux-xlnx && make ARCH=arm CROSS_COMPILE=arm-xilinx-linux-gnueabi- xilinx_zynq_defconfig 
make[1]: Entering directory `/home/chang/fpga-zynq/common/linux-xlnx'
drivers/Kconfig:31: can't open file "drivers/target/Kconfig"
make[2]: *** [xilinx_zynq_defconfig] Error 1
make[1]: *** [xilinx_zynq_defconfig] Error 2
make[1]: Leaving directory `/home/chang/fpga-zynq/common/linux-xlnx'
make: *** [arm-linux] Error 2

**Comment by clx7913** [comment]
I know what's going on.
I used "find . -name target -exec rm -r "{}" \;" in the root of "fpga-zynq" repo,so it deleted some disrelated "target" directories,such as "common/linux-xlnx/drivers/target","common/linux-xlnx/include/target".

**Comment by davidbiancolin** [comment]
Oh geez, good catch.
