### ISSUE TITLE
./fesvr-zynq pk hello stuck

### ISSUE THREAD

**Issue by clx7913** [ucb-bar/fpga-zynq#76]
The SecureCRT's log on the Win7 OS is:

PetaLinux v2013.10 (Yocto 1.4) zynq ttyPS0

zynq login: root
Password: 
login[819]: root login  on `ttyPS0'

root@zynq:~# ./fesvr-zynq pk hello                                 

It's stuck after I typed "./fesvr-zynq pk hello ",with nothing happening.
I also couldn't stop it by "crt+c".

**Comment by clx7913** [comment]
Now I resolved it.

Look at [https://github.com/ucb-bar/fpga-zynq/issues/77](url) for details.

**Comment by abdelrahmanhussein** [comment]
@clx7913 Hi,

Are you still following this issue? I may have some questions to ask. Please let me know.

Thanks.
