### ISSUE TITLE
How do you move files onto the linux file system?

### ISSUE THREAD

**Issue by thedevonwhite** [ucb-bar/fpga-zynq#84]
We have the board running the default linux that comes with the installation and run it with "./fesvr-zynq bbl". However, we have compiled C++ code into an executable using the riscv-linux cross compiler on our host system and cannot seem to find how to get the compiled executable to be visible from inside the linux kernel. We need this because the riscv-unknown compiler does not support pthreads.

The readme mentions that you can boot from an ext2 image created by buildroot, but the documentation on how to use this to get a file into linux is nonexistent. We could also build linux from source and include the file, but that seems extremely overkill.

We are looking for a suggestion on how to do this. Thank you.

**Comment by sbeamer** [comment]
In the README, you will find the documentation you need under [Getting Files On & Off the Board](https://github.com/ucb-bar/fpga-zynq#transferring).
