### ISSUE TITLE
latest fpga-zynq repo: ./fesvr-zynq pk hello  ERROR: No cores found

### ISSUE THREAD

**Issue by clx7913** [ucb-bar/fpga-zynq#85]
I've re-cloned the repo from the scratch.

Whether I used `boot.bin devicetree.dtb uImage uramdisk.image.gz` received by `make fetch-ramdisk` or used those files made by myself using` class ZynqConfig extends Config(new WithZynqAdapter ++ new DefaultFPGAConfig)` ,`./fesvr-zynq pk hello`  on zedboard always failed.

I've never encountered this kind of error.May someone help,thanks.
 _____       _           _      _
| ___ \     | |         | |    (_)
| |_/ / ___ | |_   __ _ | |     _  _ __   _   _ __  __
|  __/ / _ \| __| / _` || |    | || '_ \ | | | |\ \/ /
| |   |  __/| |_ | (_| || |____| || | | || |_| | >  <
\_|    \___| \__| \__,_|\_____/|_||_| |_| \__,_|/_/\_\

PetaLinux v2013.10 (Yocto 1.4) zynq ttyPS0

zynq login: root 
Password: 
login[818]: root login  on `ttyPS0'

root@zynq:~# ./fesvr-zynq pk hello 
ERROR: No cores found

**Comment by clx7913** [comment]
Under the last version of fpga-zynq,I `./fesvr-zynq pk hello` works fine using `class ZynqConfig extends Config(new WithZynqAdapter ++ new DefaultFPGAConfig)`.

So I doubt that this is because the rocket-chip source files have bugs.

**Comment by clx7913** [comment]
I still could not solve this problem,and I just want to back to the previous version.

I don't know how to thoroughly back to the previous version.

**Comment by clx7913** [comment]
I had a misunderstanding when I tried to change the version.

But fortunately now I've changed my version of repository into the previous one.

**Comment by alexanderFell** [comment]
Hey, @clx7913 . Just a quick question: Which old version are you using? The latest one that works for me, is commit f03982e from last year.

**Comment by JeremieMelo** [comment]
me too. I am using zybo-z7-20. After booting the linux from ramdisk, this "fesvr-zynq pk hello" will output no cores found. I don't know why.

**Comment by josecm** [comment]
I am also getting this on a zybo board with the lastest commit

**Comment by gongqingfeng** [comment]
> me too. I am using zybo-z7-20. After booting the linux from ramdisk, this "fesvr-zynq pk hello" will output no cores found. I don't know why.

I also meet the same problem: I use "make fetch-images" to get files, and run my zybo. However, "ERROR: No cores found" occurred when I run "./fesvr-zynq pk hello" or "./fesvr-zynq bbl".

**Comment by josecm** [comment]
@gongqingfeng  try https://github.com/josecm/fpga-images-zybo

**Comment by gongqingfeng** [comment]
> @gongqingfeng try https://github.com/josecm/fpga-images-zybo

Thank you! I have followed your advice, and I run "./fesvr-zynq pk hello" successfully. However, when I run "./fesvr-zynq pk hello" , I get some new errors like this:
"
terminate called after throwing an instance of 'std::runtime_error'
what(): could not open bb
l".
Have you ever met this problem. This is my issue: https://github.com/ucb-bar/fpga-zynq/issues/107
