### ISSUE TITLE
Zedboard make fetch-images gets fatal: reference is not a tree error

### ISSUE THREAD

**Issue by ewoldtcl** [ucb-bar/fpga-zynq#95]
When I follow the Quick Instructions for the zedboard, I get an error when I do "make fetch-images". 
This is the error:
git submodule update --init --depth=1 fpga-images-zedboard
Submodule 'zedboard/fpga-images-zedboard' (https://github.com/ucb-bar/fpga-images-zedboard.git) registered for path 'fpga-images-zedboard'
Cloning into 'zedboard/fpga-images-zedboard'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 1), reused 9 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Checking connectivity... done.
fatal: reference is not a tree: 7e0080ee9e29e399d80d74d9756f20cece7aeef0
Unable to checkout '7e0080ee9e29e399d80d74d9756f20cece7aeef0' in submodule path 'fpga-images-zedboard'
../common/Makefrag:163: recipe for target 'fpga-images-zedboard/boot.bif' failed
make: *** [fpga-images-zedboard/boot.bif] Error 1

When doing some investigation, it seems that if I do "git submodule update --init fpga-images-zedboard" before calling "make fetch-images", it works fine, but "make fetch-images" includes the "--depth 1" flag. I was thinking it might have to do with "make fetch-images" referencing the branch "7e0080ee.....", but the most recent commit of the submodule is "e85e4b0..." and the branch in question is the previous commit.

**Comment by davidbiancolin** [comment]
Resolved by #98.
